### ISSUE TITLE
Allow usage of environment variables in post:

### ISSUE THREAD

**Issue by adlotsof** [miniscruff/changie#520]
When running `changie new` with `post: -key author -value {{ .Env.AUTHOR }}` fill value with the environment variable contents (e.g. `PREFIX_AUTHOR`)

**Comment by miniscruff** [comment]
Good catch, this must of slipped through.

**Comment by miniscruff** [comment]
Hmm actually, I just remembered something, on the docs page I point out that env vars are not loaded when using new here https://changie.dev/config/#change-env and the reason, if I remember correctly, is these values are not loaded from the yaml when running batch? I have to look that up.

**Comment by miniscruff** [comment]
Ok sorry for the spam here but I think I got it...
So that warning was stating that defining env vars when running new did nothing. Which is still true, but by loading the env vars you can use them in post which adds custom values which are read from batching. All good, reviewing first thing in the morning really through me off.

**Comment by miniscruff** [comment]
Thanks for the pull request, I will get this out as soon as I finish the project pr in the next day or two hopefully.
