### ISSUE TITLE
Allow multiple lines for changelog entries

### ISSUE THREAD

**Issue by bephinix** [miniscruff/changie#93]
## Problem and Use Case

At the moment, the body of a changelog entry cannot contain any newlines.
If you use "Upgrade Notice" or "Deprecated" kinds in your changelog, it is ofter required to write more than one sentence.
As Markdown (and YAML) allows line breaks in list items if they are indented correctly, Changie should also support such entries.

## Suggestion

The body prompt for a new entry should be modified so a newline character is not interpreted as the end of the entry.
A specific character sequence (EOF or a dot) can be used instead of the newline character.

The resulting YAML file might look as follows:

```yaml
kind: Removal
body: |
  This is the first,
  and this the second line!
```

**Comment by miniscruff** [comment]
Hi again, I thought this might come up at some point. IIRC, my thought was that I wasn't sure if I should default body to be multiline, create a new project-wide option or add an optional CLI argument. Also, it will probably ripple to forcing other things to support multiline and I wasn't quite ready for it. I do also want to allow multiline as an option for custom choices.

There are quite a lot more configuration options that is possible for Changie to add but I don't want to have so many options it is hard to use. For example, I was considering moving kinds from a simple string list to choosing formats and choices per kind. But for simple use cases that will be a lot of configurations.

**Comment by bephinix** [comment]
@miniscruff As `changie` already uses an interactive CLI for adding new fragments, it might be an solution to have a selection step after selecting the kind so you can select if you want to want to use single or multiline.

> There are quite a lot more configuration options that is possible for Changie to add but I don't want to have so many options it is hard to use. For example, I was considering moving kinds from a simple string list to choosing formats and choices per kind. But for simple use cases that will be a lot of configurations.

You are absolutely right. One should be able to use `changie` out-of-the-box without needing an extensive configuration. Therefore it might be a good tradeof to provide a default config on initialization which will cover most of the use-cases.
Everthing else can be enabled as "opt-in".

Providing a set of default configs might also be an option to keep `changie` easy to use, what do you think?

**Comment by miniscruff** [comment]
> One should be able to use changie out-of-the-box without needing an extensive configuration.

That is basically what the init command is for, creating a base level no fluff Changie experience.

Hmm, an extra prompt could work but since I think the majority of fragments are a single line I think keeping it to that will work better. I think what makes more sense is to allow customizing prompts and formats based on the kind.

I think the reason why I didn't want to customize prompts and formats per kind was that for the most part, the kinds are about the same. So I didn't want a config file that was a bunch of copy-pasted configurations. I do not think I have enough usage to know under what circumstances you would want to alter/add/remove a prompt from your fragment-based on kind or any other use case to really know how the config and workflow should look.

For example: maybe only one kind needs to have a special prompt and format such as a security patch which required some external URL for compliance ( just making something up that sounds sort of reasonable ). Then the config should allow adding one custom workflow and keeping the others all the same. 

But if say you wanted to customize each and every kind but reuse a few prompts between them, then that is a different structure.

There is also the possibility of wanting to support a custom level above or instead of a kind for very large or combined projects such as Go itself https://golang.org/doc/go1.16#minor_library_changes or k8s https://kubernetes.io/docs/setup/release/notes/. This would turn Kind into more of an abstract concept of levels where currently it is just the one. Would also require custom sorting most likely but shouldn't be too bad.

So long answer is, yes I want to support multiline and there is a reason why Changie is still on v0 :smirk:

**Comment by miniscruff** [comment]
Note to self, promptui does not support multiline inputs and therefore we would need to choose another tool for prompts. I am going to close this for now and reassess further options at a later date.

**Comment by matthiasbeyer** [comment]
Hi. Any thoughts on re-opening this? I would suggest that if a user wants to have multi-line changelog entries, firing up their `$EDITOR` would be a perfectly reasonable thing to do, right?

I would love to see this in changie!

**Comment by miniscruff** [comment]
Hi @matthiasbeyer , I was planning on creating a task very similar to this once we swap prompt tools as part of #119 as survey supports more options including EDITOR and multi-line. Ideally Changie would support any valid prompt type from survey, maybe as part of a v2 rewrite of the config if we need to.

**Comment by miniscruff** [comment]
Reopening as it is planned with the swap to survey

**Comment by miniscruff** [comment]
Waiting on #119

**Comment by miniscruff** [comment]
Work will begin soon using a new tool related to this issue: https://github.com/miniscruff/changie/issues/457

**Comment by miniscruff** [comment]
Part of https://github.com/miniscruff/changie/releases/tag/v1.12.0
